spring:
  h2:
    console:
      enabled: true

  datasource:
    #    url: jdbc:mysql://localhost:3306/trashcan?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    url: jdbc:h2:tcp://localhost/~/streetlamp
    username: root
    password: hy00un123

  jpa:
    hibernate:
      ddl-auto: create
